import type { Metadata, Viewport } from "next";
import "./_globals.scss";
import { ReactNode } from "react";
import Providers from "./../shared/components/progressBar/ProgressBar";
import Provider from "@/app/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  verification: {
    yandex: "b2563083b856b8fa",
    google: "mhCrUZ_agoGt5Zst9mllZvMhl4HLaQFuIsKExpPRiZI",
  },
};

export const viewport: Viewport = {
  themeColor: "#fff",
  colorScheme: "light",
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Provider>{children}</Provider>
        </Providers>
      </body>
    </html>
  );
}
